import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFileSync} from 'node:fs';
import { splitSql, migrationObjects, compareObject, sqlBodyHashInput } from '../scripts/clinic-migration-manifest.js';
assert.equal(splitSql("select 'a;b'; DO $$ BEGIN perform 1; END $$; -- ignored;\n select 2;").length, 3);
const manifest = migrationObjects("CREATE TABLE public.synthetic (id uuid PRIMARY KEY, created_by uuid NOT NULL, note text DEFAULT 'a,b', CONSTRAINT synthetic_name CHECK(note <> '')); ALTER TABLE public.synthetic ALTER COLUMN created_by DROP NOT NULL; CREATE OR REPLACE FUNCTION private.synthetic(p_id uuid, p_at timestamptz DEFAULT NULL) RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path = pg_catalog, public AS $$ SELECT true; $$; REVOKE ALL ON FUNCTION private.synthetic(uuid,timestamptz) FROM PUBLIC,anon;");
assert.ok(manifest.objects.some(object => object.key === 'public.synthetic.note' && object.attributes.default === "'a,b'"));
assert.ok(manifest.objects.some(object => object.key === 'public.synthetic.created_by' && object.attributes.nullable === true));
const fn = manifest.objects.find(object => object.kind === 'function')!;
assert.equal(fn.key, 'private.synthetic(uuid,timestamp with time zone)');
const runtime = { function: [{ key: fn.key, body: fn.attributes.body, definer: true, searchPath: 'pg_catalog, public' }] };
assert.equal(compareObject(fn, runtime).status, 'MATCHES_RUNTIME');
assert.equal(compareObject(fn, { function: [{ ...runtime.function[0], body: 'SELECT false;' }] }).status, 'DRIFT');
assert.equal(compareObject(fn, { function: [{ ...runtime.function[0], searchPath: 'pg_temp' }] }).status, 'DRIFT');
assert.equal(compareObject(fn, {}).status, 'DRIFT');
assert.notEqual(sqlBodyHashInput("select 'a  b--c';"), sqlBodyHashInput("select 'a b--c';"));
assert.equal(compareObject(fn, {function:[{...runtime.function[0],searchPath:'pg_catalog, private'}]}).status,'DRIFT');
assert.equal(migrationObjects('CREATE TABLE public.check_fixture(id boolean PRIMARY KEY CHECK(id));').objects.find(object=>object.name==='check_fixture_id_check')?.attributes.type,'c');
assert.equal(migrationObjects('GRANT SELECT(id,name) ON public.fixture TO authenticated;').objects.length,2);
const policy = migrationObjects('CREATE POLICY synthetic_read ON public.synthetic FOR SELECT TO authenticated USING (false);').objects[0];
assert.equal(compareObject(policy, { policy: [{ key: policy.key, cmd: 'SELECT', roles: ['authenticated'] }] }).status, 'PARTIAL_MATCH');
assert.equal(compareObject(policy, { policy: [{ key: policy.key, cmd: 'SELECT', roles: ['anon'] }] }).status, 'DRIFT');
const evidence=JSON.parse(readFileSync('docs/clinic-f6-evidence/migration-provenance.json','utf8'));
assert.equal(evidence.staging,'hwkdwinfckmjoriqxbjk');assert.equal(evidence.readOnly,true);assert.equal(evidence.provenance01to22,'RECONCILED_WITH_LIMITATIONS');
for(const row of evidence.migrations){assert.equal(row.sha256,createHash('sha256').update(readFileSync(`supabase/clinic-migrations/${row.filename}`,'utf8').replace(/\r\n/g,'\n')).digest('hex'));assert.notEqual(row.status,'DRIFT');if(row.number<=22){assert.equal(row.formal_staging_history,'NOT_PRESENT');assert.deepEqual(row.history,[]);}else assert.equal(row.formal_staging_history,'RECONCILED');}
const forward34 = readFileSync('supabase/migrations/20260921200743_clinic_34_reconcile_clinic_runtime_provenance.sql','utf8');
const migration32 = readFileSync('supabase/clinic-migrations/20260921_32_admin_clinic_directory.sql','utf8');
const migration33 = readFileSync('supabase/clinic-migrations/20260921_33_clinic_plan_context_entitlement.sql','utf8');
const provenance = readFileSync('docs/CLINIC_MIGRATION_PROVENANCE.md','utf8');
assert.match(forward34, /clinic_34 reconciliation requires staging/);
assert.match(forward34, /list_admin_clinic_directory/);
assert.match(forward34, /get_clinic_contexts/);
assert.doesNotMatch(forward34, /INSERT\s+INTO\s+supabase_migrations|UPDATE\s+supabase_migrations|DELETE\s+FROM\s+supabase_migrations/i);
assert.doesNotMatch(forward34, /organization_memberships\s*(?:\(|SET)|organization_invitations\s+SET/i);
assert.match(migration32, /CREATE OR REPLACE FUNCTION public\.list_admin_clinic_directory/);
assert.doesNotMatch(migration32, /INSERT\s+INTO\s+public\.organization_memberships|DELETE\s+FROM\s+public\.organization_memberships/i);
assert.match(migration33, /ADD COLUMN IF NOT EXISTS professional_access_mode/);
assert.match(migration33, /IF NOT EXISTS[\s\S]+professionals_access_mode_check/);
assert.match(migration33, /DROP TRIGGER IF EXISTS organization_invitations_access_mode/);
assert.match(migration33, /WHERE i\.intended_clinical_access IS TRUE\s+AND i\.status = 'pending'/);
assert.doesNotMatch(migration33, /UPDATE\s+public\.organization_memberships|DELETE\s+FROM\s+public\.organization_memberships/i);
assert.match(provenance, /RUNTIME_PRESENT \/ RECONCILED_BY_FORMAL_FORWARD_MIGRATION_34/);
assert.match(provenance, /APPLIED AS 20260921200849/);
console.log('migration SQL parsing, exact function drift, ACL and bounded semantic limitations PASS');
