import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { draftMatchesEvolutionContext, type EvolutionContext } from "../src/services/evolutionContext.js";
const sql=readFileSync("supabase/clinic-migrations/20260917_26_isolated_organization_evolutions.sql","utf8");
assert.match(sql,/FOREIGN KEY \(organization_patient_id, organization_id, patient_id\)[\s\S]*REFERENCES public.organization_patients\(id, organization_id, patient_id\) ON DELETE NO ACTION/);
assert.match(sql,/organization_id IS NULL AND organization_patient_id IS NULL/);
assert.match(sql,/organization_id IS NOT NULL AND organization_patient_id IS NOT NULL/);
for (const column of ["organization_id","organization_patient_id","patient_id","professional_id"]) assert.match(sql,new RegExp(`NEW.${column} IS DISTINCT FROM OLD.${column}`));
assert.match(sql,/VALUES\(p_evolution_id, auth.uid\(\), v_op.patient_id, v_op.organization_id, v_op.id/);
assert.doesNotMatch(sql,/UPDATE public.evolutions SET organization/);
const personal:EvolutionContext={ type:"personal",patientId:"p" };
const clinic:EvolutionContext={ type:"organization",patientId:"p",organizationId:"o",organizationPatientId:"op" };
const local={ patientId:"p",professionalId:"a",contextKind:"organization",organizationPatientId:"op",evolutionData:{organization_id:"o",organization_patient_id:"op",patient_id:"p"} };
assert.equal(draftMatchesEvolutionContext(local,clinic,"a"),true);
assert.equal(draftMatchesEvolutionContext(local,personal,"a"),false);
assert.equal(draftMatchesEvolutionContext(local,clinic,"b"),false);
assert.equal(draftMatchesEvolutionContext({...local,organizationPatientId:"other"},clinic,"a"),false);
assert.equal(draftMatchesEvolutionContext(local,{...clinic,organizationId:"other"},"a"),false);
assert.equal(draftMatchesEvolutionContext({...local,evolutionData:{...local.evolutionData,patient_id:"other"}},clinic,"a"),false);
assert.equal(draftMatchesEvolutionContext({...local,evolutionData:undefined},clinic,"a"),false);
assert.equal(draftMatchesEvolutionContext({patientId:"p",evolutionData:{professional_id:"a"}},personal,"a"),true);
assert.equal(draftMatchesEvolutionContext({patientId:"p",evolutionData:{professional_id:"a",organization_id:"o"}},personal,"a"),false);
console.log("clinic evolution context integrity: PASS");
