import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { getHistoryPatientPath } from "../src/utils/clinicHistoryRouting";

const layout = readFileSync("src/components/Layout.tsx", "utf8");
const selector = readFileSync("src/components/clinic/ClinicContextSelector.tsx", "utf8");
const subscription = readFileSync("src/pages/ContextSubscription.tsx", "utf8");
const personalRoute = readFileSync("src/components/clinic/PersonalContextRoute.tsx", "utf8");
const clinicRoute = readFileSync("src/components/clinic/ClinicRoute.tsx", "utf8");
const app = readFileSync("src/App.tsx", "utf8");
const dashboard = readFileSync("src/pages/Dashboard.tsx", "utf8");
const history = readFileSync("src/pages/History.tsx", "utf8");
const personalPatientDetail = readFileSync("src/pages/PatientDetail.tsx", "utf8");
const clinicPatientDetail = readFileSync("src/pages/ClinicPatientDetail.tsx", "utf8");
const patientLayout = readFileSync("src/components/patients/PatientDetailLayout.tsx", "utf8");
const version = readFileSync("src/components/layout/AppVersion.tsx", "utf8");

assert.match(layout, /isClinicalProfessional/);
assert.match(layout, /isClinicalProfessional \? clinicalProfessionalNavItems : clinicNavItems/);
assert.match(layout, /path: '\/painel\/clinica\/pacientes'/);
assert.match(layout, /membershipRole === 'professional'/);
assert.match(selector, /Vinculado à clínica/);
assert.match(subscription, /Seu acesso ao Evolução Clínica está vinculado à licença da clínica\./);
assert.match(subscription, /!organization\.clinicalAccessEnabled/);
assert.match(subscription, /!organization\.licenseActive/);
assert.doesNotMatch(subscription, /StripeSubscriptionButton/);
assert.match(personalRoute, /isPersonalShellRouteAllowedForClinicalProfessional/);
assert.match(personalRoute, /pathname === "\/painel\/tutorial"/);
assert.match(app, /ClinicalAdminContextGuard><Dashboard \/><\/ClinicalAdminContextGuard>/);
assert.match(app, /ClinicalAdminContextGuard><History \/><\/ClinicalAdminContextGuard>/);
assert.match(app, /organization\.membershipRole !== 'professional'/);
assert.doesNotMatch(app, /PanelDashboardRoute|PanelHistoryRoute|ClinicProfessionalHistory/);
assert.match(dashboard, /isClinicalProfessional/);
assert.match(dashboard, /fetchClinicPatients/);
assert.match(dashboard, /clinicEvolutionRequest/);
assert.match(history, /fetchClinicPatients/);
assert.match(history, /clinicEvolutionRequest/);
assert.doesNotMatch(history, /\.from\("evolutions"\)/);
assert.match(clinicRoute, /location\.pathname === "\/painel\/clinica"/);
assert.match(version, /v1\.10\.918/);

assert.match(personalPatientDetail, /PatientDetailHeader/);
assert.match(personalPatientDetail, /PatientDetailGrid/);
assert.match(clinicPatientDetail, /PatientDetailHeader/);
assert.match(clinicPatientDetail, /PatientDetailGrid/);
assert.match(clinicPatientDetail, /organizationPatientId.*evolucoes.*nova/);
assert.match(clinicPatientDetail, /patient\.canCreateEvolution/);
assert.match(clinicPatientDetail, /canEdit/);
assert.match(clinicPatientDetail, /patient\.canReadEvolutions && <ClinicPatientEvolutions/);
assert.doesNotMatch(clinicPatientDetail, /Dados cadastrais compartilhados nesta organização/);
assert.match(patientLayout, /safe-area-inset-top/);
assert.match(patientLayout, /xl:grid-cols-3/);
assert.match(patientLayout, /Seções do paciente/);

const patientsMap = { "patient-123": { organizationPatientId: "org-patient-987" } };
assert.equal(getHistoryPatientPath("patient-123", false, patientsMap), "/painel/patients/patient-123");
assert.equal(getHistoryPatientPath("patient-123", true, patientsMap), "/painel/clinica/pacientes/org-patient-987");
assert.notEqual(getHistoryPatientPath("patient-123", true, patientsMap), "/painel/clinica/pacientes/patient-123");

console.log("clinic professional visual shell and clinic plan gating: PASS");
