import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const formSource = readFileSync('src/pages/PatientForm.tsx', 'utf8');
const cropEditorSource = readFileSync('src/components/common/ImageCropEditor.tsx', 'utf8');
const customLogoSource = readFileSync('src/pages/CustomLogo.tsx', 'utf8');
const patientPhotoSource = readFileSync('src/components/patients/PatientPhoto.tsx', 'utf8');
const patientPhotoServiceSource = readFileSync('src/services/patientPhoto.ts', 'utf8');
const patientPhotoPipelineSource = readFileSync('src/services/patientPhotoPipeline.ts', 'utf8');
const patientsSource = readFileSync('src/pages/Patients.tsx', 'utf8');
const detailSource = readFileSync('src/pages/PatientDetail.tsx', 'utf8');
const serverSource = readFileSync('server.ts', 'utf8');
const migrationSource = readFileSync('supabase/migrations/20260920131514_add_private_patient_photos.sql', 'utf8');
const jpegMigrationSource = readFileSync('supabase/migrations/20260924184838_allow_patient_photo_jpeg.sql', 'utf8');

assert.match(migrationSource, /add column if not exists photo_path text/i);
assert.match(migrationSource, /'patient-photos',[\s\S]*?false,[\s\S]*?2097152/);
assert.match(migrationSource, /patient_photos_select_own[\s\S]*?to authenticated[\s\S]*?auth\.uid\(\)/);
assert.match(migrationSource, /patient_photos_insert_own[\s\S]*?to authenticated[\s\S]*?auth\.uid\(\)/);
assert.match(migrationSource, /patient_photos_delete_own[\s\S]*?to authenticated[\s\S]*?auth\.uid\(\)/);
assert.match(jpegMigrationSource, /allowed_mime_types\s*=\s*array\['image\/jpeg',\s*'image\/png',\s*'image\/webp'\]/i);

assert.match(cropEditorSource, /createCroppedImageBlob/);
assert.ok(
  cropEditorSource.includes("if (/^https?:\\/\\//i.test(imageUrl))"),
  'editor deve aplicar CORS somente a imagens HTTP(S)'
);
assert.match(cropEditorSource, /Arraste para mover/);
assert.match(cropEditorSource, /Aproximação/);
assert.match(cropEditorSource, /transform: 'translate\(-50%, -50%\)'/, 'A imagem deve permanecer centralizada antes de aplicar o deslocamento do recorte.');
assert.match(cropEditorSource, /const DEFAULT_CROP_ZOOM = 1\.15/, 'O editor deve manter margem para deslocamento horizontal mesmo em fotos quadradas.');
assert.match(cropEditorSource, /min="1\.05"/, 'O zoom mínimo deve preservar espaço para movimentar o recorte.');
assert.match(cropEditorSource, /imageLeftPercent = 50 - cropPosition\.x \* horizontalOverflowPercent/, 'A prévia deve traduzir horizontalmente o recorte aplicado.');
assert.match(cropEditorSource, /imageTopPercent = 50 - cropPosition\.y \* verticalOverflowPercent/, 'A prévia deve traduzir verticalmente o recorte aplicado.');
assert.match(cropEditorSource, /onTouchStart=\{handleTouchStart\}/, 'O editor deve aceitar arraste por toque no mobile.');
assert.match(cropEditorSource, /aria-label="Posição horizontal do recorte"/, 'O editor deve oferecer ajuste horizontal explícito.');
assert.match(cropEditorSource, /imageWidthPercent|horizontalOverflowPercent/, 'A prévia deve calcular a área horizontal disponível pelo aspecto natural da imagem.');
assert.match(cropEditorSource, /imageHeightPercent|verticalOverflowPercent/, 'A prévia deve calcular a área vertical disponível pelo aspecto natural da imagem.');
assert.match(cropEditorSource, /naturalWidth.*naturalHeight/, 'A prévia deve usar as dimensões naturais carregadas da imagem.');
assert.match(cropEditorSource, /className="absolute max-w-none/, 'A prévia não pode ser limitada ao tamanho da moldura pelo estilo global das imagens.');
assert.match(cropEditorSource, /height: 'auto'/, 'A prévia deve preservar a proporção natural da imagem.');
assert.match(cropEditorSource, /getBoundingClientRect\(\)/, 'A prévia deve usar a proporção efetivamente renderizada, inclusive para fotos com orientação EXIF.');
assert.match(cropEditorSource, /imageRef/);
assert.match(cropEditorSource, /requestAnimationFrame\(syncImageAspect\)/, 'A prévia deve recalcular a proporção quando o carregamento ocorrer antes do efeito inicial no mobile.');
assert.match(cropEditorSource, /outputMimeType.*image\/jpeg|image\/jpeg.*outputMimeType/, 'O editor deve permitir exportar a foto do paciente em JPEG comprimido.');
assert.match(cropEditorSource, /outputQuality/, 'O editor deve aceitar qualidade controlada na compressão.');
assert.match(customLogoSource, /<ImageCropEditor/);
assert.match(formSource, /<ImageCropEditor/);
assert.match(formSource, /initialAspect=\{1\}/);
assert.match(formSource, /createPatientPhotoObjectUrl/);
assert.match(formSource, /materializePatientPhoto\(file/);
assert.match(formSource, /patient-photo-diagnostics/);
assert.match(formSource, /preparePatientPhotoSource/);
assert.match(formSource, /import\('heic2any'\)/, 'Fotos HEIC/HEIF devem ser convertidas antes do recorte.');
assert.match(formSource, /value\.arrayBuffer\(\)/, 'O WebView deve ter um fallback que copia os bytes antes de limpar o input.');
assert.match(formSource, /new FileReader\(\)/, 'WebViews que falham no arrayBuffer devem ter fallback via FileReader.');
assert.match(formSource, /readAsArrayBuffer/);
assert.match(formSource, /readAsDataURL/);
assert.match(formSource, /hasHeicContainerSignature/);
assert.match(formSource, /handlePhotoSelection[\s\S]*?const input = event\.currentTarget[\s\S]*?materializePatientPhoto\(file[\s\S]*?preparePatientPhotoSource\(materializedPhoto\)[\s\S]*?createPatientPhotoObjectUrl\(preparedPhoto\)[\s\S]*?createCroppedImageBlob\(\{[\s\S]*?imageUrl: sourceUrl[\s\S]*?outputMimeType: 'image\/jpeg'[\s\S]*?outputQuality: 0\.9[\s\S]*?createPatientPhotoObjectUrl\(initialCrop\)[\s\S]*?setPendingPhotoBlob\(initialCrop\)[\s\S]*?setPhotoPreviewUrl\(previewUrl\)[\s\S]*?finally[\s\S]*?input\.value = ''/);
assert.match(formSource, /Não foi possível preparar/);
assert.match(formSource, /file\.name/);
assert.match(formSource, /outputMimeType="image\/jpeg"/);
assert.match(formSource, /outputQuality=\{0\.9\}/);
assert.match(formSource, /A prévia é criada automaticamente/);
assert.match(formSource, /uploadPatientPhoto\(/);
assert.match(formSource, /photo_path: nextPhotoPath \|\| null/);

assert.match(patientPhotoServiceSource, /createSignedUrl\(photoPath, 60 \* 60\)/);
assert.match(patientPhotoServiceSource, /upsert: false/);
assert.match(patientPhotoServiceSource, /-photo\.jpg/);
assert.match(patientPhotoServiceSource, /contentType: 'image\/jpeg'/);
assert.match(patientPhotoServiceSource, /image\/heic/);
assert.match(patientPhotoServiceSource, /isPatientPhotoHeic/);
assert.match(patientPhotoPipelineSource, /FILE_ARRAY_BUFFER/);
assert.match(patientPhotoPipelineSource, /RESPONSE_ARRAY_BUFFER/);
assert.match(patientPhotoPipelineSource, /FILE_READER/);
assert.match(patientPhotoPipelineSource, /new File\(\[bytes\]/);
assert.doesNotMatch(patientPhotoServiceSource, /getPublicUrl/);
assert.match(patientPhotoSource, /createPatientPhotoSignedUrl\(photoPath\)/);
assert.match(patientsSource, /<PatientPhoto photoPath=\{patient\.photo_path\}/);
assert.match(patientsSource, /shape="rounded" className="h-20 w-20"/, 'A lista deve usar foto quadrada maior com cantos suaves.');
assert.match(patientsSource, /PATIENTS_GUIDE_STEPS/);
assert.match(patientsSource, /PATIENTS_SUPPORT_HREF/);
assert.match(patientsSource, /Como funciona a lista de pacientes/);
assert.match(detailSource, /<PatientPhoto photoPath=\{patient\.photo_path\}/);
assert.match(patientPhotoSource, /object-cover object-center/, 'A foto exibida deve usar o centro do recorte aplicado.');
assert.match(patientPhotoSource, /shape === 'rounded' \? 'rounded-xl' : 'rounded-full'/, 'O formato quadrado deve ser opcional para preservar outros contextos.');
assert.match(detailSource, /className="h-16 w-16 shrink-0 sm:h-20 sm:w-20 xl:h-16 xl:w-16"/, 'A foto do cabeçalho deve crescer sem perder o limite responsivo.');
assert.match(formSource, /setPhotoEditorUrl\(storedPhotoUrl\)/, 'Uma foto já salva deve abrir diretamente no editor também no mobile.');
assert.match(formSource, /setPhotoEditorUrl\(photoPreviewUrl\)/, 'O editor deve usar a imagem atualmente visualizada ao reajustar a foto.');
assert.match(serverSource, /\.from\("patient-photos"\)[\s\S]*?\.remove\(photoPaths\)/);

console.log('Patient private photo tests passed.');
