import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const appSource = readFileSync('src/App.tsx', 'utf8');
const patientDetailSource = readFileSync('src/pages/PatientDetail.tsx', 'utf8');
const anamnesisPageSource = readFileSync('src/pages/PatientAnamnesis.tsx', 'utf8');
const anamnesisServiceSource = readFileSync('src/services/anamnesis.ts', 'utf8');
const anamnesisCardSource = readFileSync('src/components/patients/PatientAnamnesisSummaryCard.tsx', 'utf8');
const anamnesisPdfSource = readFileSync('src/utils/anamnesisPdf.ts', 'utf8');
const prontuarioPdfSource = readFileSync('src/utils/prontuarioPdf.ts', 'utf8');
const baseMigrationSource = readFileSync('supabase/migrations/20260918192205_add_versioned_patient_anamnesis.sql', 'utf8');
const hardeningMigrationSource = readFileSync('supabase/migrations/20260918195218_harden_patient_anamnesis.sql', 'utf8');
const integrityMigrationSource = readFileSync('supabase/migrations/20260918195632_finalize_patient_anamnesis_integrity.sql', 'utf8');

assert.match(appSource, /PatientAnamnesis/);
assert.match(appSource, /patients\/:id\/anamnesis/);

assert.match(patientDetailSource, /Abrir anamnese/);
assert.match(patientDetailSource, /Acessar anamnese/);
assert.match(patientDetailSource, /Somente para assinantes do Plano Anual/);
assert.match(patientDetailSource, /hidden xl:flex/);
assert.match(patientDetailSource, /<PatientAnamnesisSummaryCard/);
assert.match(patientDetailSource, /xl:hidden/);

assert.match(anamnesisPageSource, /Modelo do formulário/);
assert.match(anamnesisPageSource, /AUTOSAVE_DELAY_MS = 900/);
assert.match(anamnesisPageSource, /AUTOSAVE_MAX_ATTEMPTS = 3/);
assert.match(anamnesisPageSource, /saveQueueRef/);
assert.match(anamnesisPageSource, /flushPendingSave/);
assert.match(anamnesisPageSource, /useBeforeUnload/);
assert.match(anamnesisPageSource, /visibilitychange/);
assert.match(anamnesisPageSource, /pagehide/);
assert.match(anamnesisPageSource, /popstate/);
assert.match(anamnesisPageSource, /handleDocumentClick/);
assert.doesNotMatch(anamnesisPageSource, /unstable_usePrompt/);
assert.match(anamnesisPageSource, /Salvo automaticamente/);
assert.match(anamnesisPageSource, /Concluir anamnese/);
assert.match(anamnesisPageSource, /Reabrir como rascunho/);
assert.match(anamnesisPageSource, /disabled=\{isCompleted\}/);
assert.match(anamnesisPageSource, /Iniciar nova anamnese/);
assert.match(anamnesisPageSource, /A atual será preservada no histórico/);
assert.match(anamnesisPageSource, /Visualizar registro/);
assert.match(anamnesisPageSource, /Histórico de alterações/);
assert.match(anamnesisPageSource, /Baixar PDF/);
assert.match(anamnesisPageSource, /Copiar última anamnese/);
assert.match(anamnesisPageSource, /Começar do zero/);
assert.match(anamnesisPageSource, /Salvamento automático/);
assert.match(anamnesisPageSource, /Salvo automaticamente/);
assert.match(anamnesisPageSource, /Como funciona a Anamnese/);
assert.match(anamnesisPageSource, /Abrir guia de como funciona a Anamnese/);
assert.match(anamnesisPageSource, /ANAMNESIS_GUIDE_STEPS/);
assert.match(anamnesisPageSource, /handleDownloadPdf/);
assert.match(anamnesisPageSource, /handleStartNew\('copy'\)/);
assert.match(anamnesisPageSource, /handleStartNew\('blank'\)/);
assert.match(anamnesisPageSource, /setCurrentRecord\(created\)/);
assert.match(anamnesisPageSource, /A nova anamnese foi criada e a anterior está preservada no histórico/);
assert.match(anamnesisPageSource, /Promise\.allSettled\(\[loadHistory\(\), loadRevisions\(\)\]\)/);
assert.match(anamnesisPageSource, /orderSections/);
assert.match(anamnesisPageSource, /section\.key === 'goals'/);
assert.doesNotMatch(anamnesisPageSource, /Gemini|inteligência artificial|\bIA\b/);

assert.match(anamnesisServiceSource, /getRecommendedAnamnesisTemplate/);
assert.match(anamnesisServiceSource, /templateKey === 'general'/);
assert.match(anamnesisServiceSource, /start_patient_anamnesis/);
assert.match(anamnesisServiceSource, /fetchPatientAnamnesisRevisions/);
assert.match(anamnesisServiceSource, /patient_anamnesis_revisions/);
assert.match(anamnesisServiceSource, /is_current/);

assert.match(anamnesisCardSource, /Preencher anamnese/);
assert.match(anamnesisCardSource, /Esta funcionalidade é somente para assinantes do Plano Anual/);
assert.match(anamnesisCardSource, /Acessar anamnese/);
assert.match(anamnesisCardSource, /Rascunho/);
assert.match(anamnesisCardSource, /Concluída/);
assert.match(anamnesisCardSource, /matchMedia\('\(min-width: 1280px\)'\)/);
assert.match(anamnesisCardSource, /Abrir anamnese/);
assert.match(anamnesisCardSource, /flex w-full items-center justify-between rounded-xl/);
assert.match(anamnesisCardSource, /ArrowRight/);
assert.match(anamnesisCardSource, /<\/div>\s*<\/div>\s*<Link\s+to=\{href\}/);

assert.match(anamnesisPdfSource, /generateAnamnesisPDF/);
assert.match(anamnesisPdfSource, /generateProntuarioPDF/);
assert.match(anamnesisPdfSource, /getAnamnesisPdfFileName/);
assert.match(anamnesisPdfSource, /filterAnamnesisAnswersForSchema/);
assert.match(anamnesisPdfSource, /## \$\{section\.title\}/);
assert.match(prontuarioPdfSource, /isMarkdownHeading/);
assert.match(prontuarioPdfSource, /isStandaloneBold/);

assert.match(baseMigrationSource, /create table if not exists public\.anamnesis_templates/);
assert.match(baseMigrationSource, /create table if not exists public\.patient_anamneses/);
assert.match(baseMigrationSource, /template_snapshot jsonb/);
assert.match(baseMigrationSource, /patient_anamneses_one_current_idx/);
assert.match(baseMigrationSource, /security invoker/);
assert.match(baseMigrationSource, /patient_anamneses_owner_select/);
assert.match(baseMigrationSource, /patient_anamneses_owner_insert/);
assert.match(baseMigrationSource, /patient_anamneses_owner_update/);
assert.match(baseMigrationSource, /grant select on table public\.anamnesis_templates to authenticated/);

assert.match(hardeningMigrationSource, /patient_anamneses_status_completed_at_check/);
assert.match(hardeningMigrationSource, /create table if not exists public\.patient_anamnesis_revisions/);
assert.match(hardeningMigrationSource, /patient_anamnesis_revisions_owner_select/);
assert.match(hardeningMigrationSource, /private\.guard_patient_anamnesis_write/);
assert.match(hardeningMigrationSource, /anamnesis_immutable_metadata/);
assert.match(hardeningMigrationSource, /anamnesis_reopen_required_before_edit/);
assert.match(hardeningMigrationSource, /private\.log_patient_anamnesis_revision/);
assert.match(hardeningMigrationSource, /patient_anamneses_template_idx/);
assert.match(hardeningMigrationSource, /v_existing\.template_id = p_template_id and not p_archive_current/);
assert.match(hardeningMigrationSource, /Medicina Veterinária/);
assert.match(hardeningMigrationSource, /Veterinário\(a\)/);
assert.match(hardeningMigrationSource, /Técnico de enfermagem/);
assert.match(hardeningMigrationSource, /Auxiliar de enfermagem/);

assert.match(integrityMigrationSource, /patient_anamnesis_revisions_professional_idx/);
assert.match(integrityMigrationSource, /patient_anamnesis_revisions_changed_by_idx/);
assert.match(integrityMigrationSource, /anamnesis_completed_at_managed_internally/);
assert.match(integrityMigrationSource, /old\.status = 'draft' and new\.status = 'completed'/);
assert.match(integrityMigrationSource, /new\.completed_at := now\(\)/);
assert.match(integrityMigrationSource, /old\.status = 'completed' and new\.status = 'draft'/);
assert.match(integrityMigrationSource, /new\.completed_at := null/);

console.log('Patient anamnesis tests passed.');
