import React, { useEffect, useState } from 'react';
import { Check, Shield } from 'lucide-react';
import { getConsentPreferences, setConsentPreferences } from '../services/analytics';

export const CookieConsent = () => {
  const [visible, setVisible] = useState(false);
  const [preferencesOpen, setPreferencesOpen] = useState(false);
  const [analytics, setAnalytics] = useState(false);
  const [marketing, setMarketing] = useState(false);
  useEffect(() => {
    const load = () => { const current = getConsentPreferences(); setAnalytics(current?.analytics ?? false); setMarketing(current?.marketing ?? false); setVisible(current === null); };
    load(); window.addEventListener('cookie-consent-open', () => { load(); setPreferencesOpen(true); setVisible(true); });
  }, []);
  const save = (nextAnalytics = analytics, nextMarketing = marketing) => { setConsentPreferences({ analytics: nextAnalytics, marketing: nextMarketing }); setVisible(false); setPreferencesOpen(false); window.dispatchEvent(new Event('cookie-consent-accepted')); };
  if (!visible) return <button type="button" onClick={() => window.dispatchEvent(new Event('cookie-consent-open'))} className="fixed bottom-2 left-2 z-[60] rounded-full border border-brand-border bg-white px-3 py-1.5 text-[10px] font-semibold text-brand-text-muted shadow-sm hover:text-brand-primary" aria-label="Abrir preferências de privacidade">Privacidade</button>;
  const item = (label: string, description: string, checked: boolean, onChange: (checked: boolean) => void) => <label className="flex items-start space-x-4 p-3 rounded-2xl border border-gray-100 hover:bg-gray-50/50 transition-colors cursor-pointer select-none"><div className="pt-1.5 shrink-0"><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} className="w-4.5 h-4.5 rounded border-gray-300 text-brand-primary focus:ring-brand-primary cursor-pointer accent-brand-primary" /></div><div className="flex-1"><div className="flex justify-between items-center"><span className="text-sm font-bold text-gray-800">{label}</span><span className={`text-[10px] font-bold px-2 py-0.5 rounded ${checked ? 'text-brand-accent-hover bg-brand-accent/10' : 'text-gray-400 bg-gray-100'}`}>{checked ? 'Ativo' : 'Inativo'}</span></div><p className="text-xs text-gray-500 mt-1 leading-relaxed">{description}</p></div></label>;
  return <>{!preferencesOpen && <div className="fixed bottom-0 left-0 right-0 bg-white border-t border-gray-100 p-4 z-[70] shadow-2xl"><div className="max-w-5xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4"><p className="text-sm text-gray-600 leading-relaxed">Usamos tecnologias opcionais somente com sua autorização para medir desempenho e, separadamente, ativar recursos de publicidade.</p><div className="flex gap-3 shrink-0 w-full md:w-auto"><button onClick={() => setPreferencesOpen(true)} className="flex-1 md:flex-none px-6 py-2.5 border border-gray-200 text-gray-600 rounded-xl font-semibold text-sm">Preferências</button><button onClick={() => save(true, true)} className="flex-1 md:flex-none bg-brand-primary text-white px-8 py-2.5 rounded-xl font-bold text-sm">Aceitar Todos</button></div></div></div>}{preferencesOpen && <div className="fixed inset-0 bg-stone-900/60 backdrop-blur-sm flex items-center justify-center p-4 z-[80]"><div className="bg-white rounded-3xl border border-gray-100 shadow-2xl max-w-lg w-full p-6 space-y-6"><div className="flex items-center space-x-3 border-b border-gray-100 pb-4"><div className="p-2.5 bg-brand-primary/10 rounded-xl text-brand-primary"><Shield className="w-5 h-5" /></div><div><h3 className="text-lg font-bold font-display text-brand-primary">Preferências de privacidade</h3><p className="text-xs text-gray-500">Você pode alterar estas escolhas a qualquer momento.</p></div></div><div className="space-y-4 max-h-[300px] overflow-y-auto pr-1"><div className="flex items-start space-x-4 p-3 rounded-2xl bg-gray-50/80 border border-gray-100"><div className="p-2 bg-brand-primary/10 rounded-lg text-brand-primary mt-0.5"><Check className="w-4 h-4" /></div><div><div className="flex justify-between items-center"><span className="text-sm font-bold text-gray-800">Essenciais (obrigatório)</span><span className="text-[10px] font-bold text-brand-primary bg-brand-primary/10 px-2 py-0.5 rounded">Ativo</span></div><p className="text-xs text-gray-500 mt-1">Autenticação, segurança e suas preferências.</p></div></div>{item('Estatísticas & Analytics', 'Medição com Firebase/GA4, sem conteúdo clínico; pode usar identificadores pseudônimos.', analytics, setAnalytics)}{item('Marketing', 'Google Ads/remarketing e Meta Pixel, quando configurados, sem conteúdo clínico.', marketing, setMarketing)}</div><div className="flex justify-between items-center pt-4 border-t border-gray-100 gap-3"><button onClick={() => setPreferencesOpen(false)} className="px-5 py-2.5 border border-gray-200 text-gray-500 rounded-xl font-semibold text-xs">Voltar</button><div className="flex gap-2"><button onClick={() => save(true, true)} className="px-5 py-2.5 border border-brand-primary/20 text-brand-primary rounded-xl font-bold text-xs">Aceitar Todos</button><button onClick={() => save()} className="bg-brand-primary text-white px-5 py-2.5 rounded-xl font-bold text-xs">Salvar escolhas</button></div></div></div></div>}</>;
};
