import { createHash } from 'node:crypto';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { loadRuntime, sql } from './clinic-preproduction-runtime.js';
import { canonicalType, compareObject, migrationObjects, sqlBodyHashInput } from './clinic-migration-manifest.js';

const runtime = loadRuntime();
const rows = await sql(runtime, `select jsonb_build_object(
 'table',(select jsonb_agg(jsonb_build_object('key',n.nspname||'.'||c.relname,'rls',c.relrowsecurity)) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private') and c.relkind='r'),
 'column',(select jsonb_agg(jsonb_build_object('key',n.nspname||'.'||c.relname||'.'||a.attname,'type',format_type(a.atttypid,a.atttypmod),'nullable',not a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid))) from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace left join pg_attrdef d on d.adrelid=a.attrelid and d.adnum=a.attnum where n.nspname in ('public','private') and c.relkind='r' and a.attnum>0 and not a.attisdropped),
 'constraint',(select jsonb_agg(jsonb_build_object('key',n.nspname||'.'||c.relname||'.'||k.conname,'type',k.contype,'referencedRelation',case when k.confrelid<>0 then rn.nspname||'.'||rc.relname end,'deferrable',k.condeferrable,'initiallyDeferred',k.condeferred,'definition',pg_get_constraintdef(k.oid))) from pg_constraint k join pg_class c on c.oid=k.conrelid join pg_namespace n on n.oid=c.relnamespace left join pg_class rc on rc.oid=k.confrelid left join pg_namespace rn on rn.oid=rc.relnamespace where n.nspname in ('public','private')),
 'function',(select jsonb_agg(jsonb_build_object('key',n.nspname||'.'||p.proname||'('||oidvectortypes(p.proargtypes)||')','body',p.prosrc,'definer',p.prosecdef,'searchPath',(select substr(v,13) from unnest(p.proconfig) v where v like 'search_path=%'))) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private')),
 'policy',(select jsonb_agg(jsonb_build_object('key',n.nspname||'.'||c.relname||'.'||p.polname,'cmd',case p.polcmd when 'r' then 'SELECT' when 'a' then 'INSERT' when 'w' then 'UPDATE' when 'd' then 'DELETE' else 'ALL' end,'roles',(select jsonb_agg(coalesce(r.rolname,'public') order by coalesce(r.rolname,'public')) from unnest(p.polroles) x left join pg_roles r on r.oid=x),'using',pg_get_expr(p.polqual,p.polrelid),'check',pg_get_expr(p.polwithcheck,p.polrelid))) from pg_policy p join pg_class c on c.oid=p.polrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private')),
 'index',(select jsonb_agg(jsonb_build_object('key',n.nspname||'.'||c.relname,'unique',i.indisunique,'definition',pg_get_indexdef(c.oid))) from pg_index i join pg_class c on c.oid=i.indexrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','private')),
 'trigger',(select jsonb_agg(jsonb_build_object('key',n.nspname||'.'||c.relname||'.'||t.tgname,'functionName',fn.nspname||'.'||p.proname,'deferrable',t.tgdeferrable,'initiallyDeferred',t.tginitdeferred,'definition',pg_get_triggerdef(t.oid))) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace join pg_proc p on p.oid=t.tgfoid join pg_namespace fn on fn.oid=p.pronamespace where n.nspname in ('public','private') and not t.tgisinternal),
 'history',(select jsonb_agg(jsonb_build_object('version',version,'name',name) order by version) from supabase_migrations.schema_migrations)
) inventory`);
const inventory = rows[0].inventory;
for (const fn of inventory.function) { fn.key = fn.key.replace(/\((.*)\)$/, (_: string, args: string) => `(${args.split(',').map(canonicalType).filter(Boolean).join(',')})`); fn.body = sqlBodyHashInput(fn.body); }
for (const column of inventory.column) column.type = canonicalType(column.type);
inventory.grant = [];
const files = readdirSync('supabase/clinic-migrations').filter(name => /^\d{8}_\d+_.*\.sql$/.test(name)).sort();
const migrations = files.map(filename => { const source = readFileSync(`supabase/clinic-migrations/${filename}`, 'utf8'); return { number: Number(filename.split('_')[1]), filename, sha256: createHash('sha256').update(source.replace(/\r\n/g,'\n')).digest('hex'), checkout_sha256: createHash('sha256').update(source).digest('hex'), source, ...migrationObjects(source) }; });
const latest = new Map<string, any>();
for (const migration of migrations) for (const object of migration.objects) {
  const key = `${object.kind}:${object.key}`, prior = latest.get(key);
  latest.set(key, { ...object, attributes: object.kind === 'column' && prior ? { ...prior.attributes, ...object.attributes } : object.attributes, migration: migration.number });
}
const grants = [...latest.values()].filter(value => value.kind === 'grant');
for (const grant of grants) { const fn = latest.get(`function:${grant.attributes.objectKey}`); if (grant.attributes.objectType==='function' && fn?.action==='drop' && fn.migration>grant.migration) { grant.attributes.allowed=false; grant.migration=fn.migration; } }
// Effective privileges include inherited PUBLIC grants; PUBLIC itself is checked via its ACL entry.
const grantQueries: string[] = [];
for (const object of grants) {
  const { objectType, objectKey, role, privilege } = object.attributes;
  if (!['function','table','schema','column'].includes(objectType) || !/^[a-z_][a-z_0-9]*$/.test(role) || !/^[A-Z]+$/.test(privilege) || !/^[a-z_0-9.,() \[\]]+$/.test(objectKey)) throw Error('unparsed_grant_target');
  let query: string;
  if (objectType==='column') { const parts=objectKey.split('.'); if(role==='public') throw Error('public_column_acl_review_required'); query=`select has_column_privilege('${role}','${parts.slice(0,2).join('.')}','${parts[2]}','${privilege}') allowed`; }
  else if (role !== 'public') query = objectType==='function' ? `select coalesce(has_function_privilege('${role}',to_regprocedure('${objectKey}'),'${privilege}'),false) allowed` : `select has_${objectType}_privilege('${role}','${objectKey}','${privilege}') allowed`;
  else { const type = objectType === 'function' ? 'f' : objectType === 'schema' ? 'n' : 'r'; const catalog = objectType === 'function' ? 'pg_proc' : objectType === 'schema' ? 'pg_namespace' : 'pg_class'; const acl = objectType === 'function' ? 'proacl' : objectType === 'schema' ? 'nspacl' : 'relacl'; const owner = objectType === 'function' ? 'proowner' : objectType === 'schema' ? 'nspowner' : 'relowner'; const lookup = objectType === 'function' ? `to_regprocedure('${objectKey}')` : objectType === 'schema' ? `(select oid from pg_namespace where nspname='${objectKey}')` : `to_regclass('${objectKey}')`; query = `select exists(select 1 from ${catalog} c cross join lateral aclexplode(coalesce(c.${acl},acldefault('${type}',c.${owner}))) a where c.oid=${lookup} and a.grantee=0 and a.privilege_type='${privilege}') allowed`; }
  grantQueries.push(`select '${object.key}' key, allowed from (${query}) permission`);
}
inventory.grant = await sql(runtime, grantQueries.join(' UNION ALL '));
const results = migrations.map(migration => {
  const history = inventory.history.filter((row: any) => new RegExp(`(?:clinic|[0-9]{8})_${String(migration.number).padStart(2,'0')}_`).test(row.name));
  const objects = migration.objects.map(object => { const current = latest.get(`${object.kind}:${object.key}`); return { kind: object.kind, key: object.key, finalMigration: current.migration, ...(current.migration > migration.number ? { status: 'SUPERSEDED_BY_LATER_MIGRATION', checks: [], limitations: [] } : compareObject(current, inventory)) }; });
  const active = objects.filter(object => object.status !== 'SUPERSEDED_BY_LATER_MIGRATION');
  const status = active.some(object => object.status === 'DRIFT') ? 'DRIFT' : active.some(object => object.status === 'PARTIAL_MATCH') || migration.limitations.length ? 'PARTIAL_MATCH' : !active.length && objects.length ? 'SUPERSEDED_BY_LATER_MIGRATION' : 'MATCHES_RUNTIME';
  return { number: migration.number, filename: migration.filename, sha256: migration.sha256, checkout_sha256:migration.checkout_sha256, formal_staging_history: history.length ? 'RECONCILED' : 'NOT_PRESENT', history, runtime_objects_present: `${active.filter(object => !object.checks?.includes('object_missing')).length}/${active.length} final declarations`, superseded_by: [...new Set(objects.filter(object => object.finalMigration > migration.number).map(object => object.finalMigration))].sort((a,b)=>a-b), status, production_action: /hwkdwinfckmjoriqxbjk|environment_name\s*(?:<>|!=)\s*'staging'|runtime_environment/i.test(migration.source) ? 'PRODUCTION_EQUIVALENT_REQUIRED' : 'CANONICAL_FINAL_STATE_REVIEW_REQUIRED', limitations: migration.limitations, objects };
});
const report = { phase: '6B', staging: runtime.ref, readOnly: true, history01to22: 'NOT_PRESENT', provenance01to22: results.some(row => row.number<=22 && row.status==='DRIFT') ? 'UNRESOLVED_DRIFT' : 'RECONCILED_WITH_LIMITATIONS', history23to30: results.filter(row=>row.number>=23&&row.number<=30).every(row=>row.formal_staging_history==='RECONCILED') ? 'RECONCILED' : 'UNKNOWN', productionBundle: 'DESIGN_READY_FOR_HUMAN_REVIEW', limitations: ['Formal historical execution metadata for 01–22 is absent; hashes and current runtime do not reconstruct timestamps or executors.','Catalog expression formatting and SQL semantics require human review; PARTIAL_MATCH never means history was applied.','The inventory contains current definitions, not clinical records.'], migrations: results, inventory };
writeFileSync(process.env.F6B_PROVENANCE_FILE || 'docs/clinic-f6-evidence/migration-provenance.json', JSON.stringify(report,null,2)+'\n');
assert.ok(results.every(row=>row.status!=='DRIFT'),'Unresolved catalog drift; inspect JSON before documenting reconciliation');
assert.equal(report.history23to30,'RECONCILED');
const lines = ['# Proveniência das migrations Clínica — Fase 6B','','Reconciliação somente leitura do staging `hwkdwinfckmjoriqxbjk`. Checksums SHA-256 dos arquivos atuais; nenhuma reaplicação ou inserção retroativa no ledger. Produção e main intocados.','','01–22: **RECONCILED_WITH_LIMITATIONS**, histórico formal **NOT_PRESENT**. Não é possível reconstruir data/executor pelo catálogo atual. 23–30: histórico formal **RECONCILED**. 31: correção adicional de contexto pending do owner aplicada exclusivamente em staging nesta rodada.','','| number | filename | sha256 | formal_staging_history | runtime_objects_present | superseded_by | status | production_action |','| --- | --- | --- | --- | --- | --- | --- | --- |',...results.map(row=>`| ${row.number} | ${row.filename} | ${row.sha256} | ${row.formal_staging_history} | ${row.runtime_objects_present} | ${row.superseded_by.join(', ')||'—'} | ${row.status} | ${row.production_action} |`),'','## Alcance verificável e limites','','O JSON registra inventário de tabelas/colunas/constraints/policies/índices/triggers/funções e permissões efetivas, incluindo grants por coluna. Funções finais: assinatura, corpo com literais preservados, SECURITY DEFINER e search_path fixo comparados. Colunas: tipo/nullability; constraints: tipo, relação referenciada e deferrabilidade; policies: comando/roles; índices: unicidade; triggers: função/deferrabilidade; ACL: privilégio efetivo. Drops e substituições posteriores são considerados.','','PARTIAL_MATCH declara explicitamente revisão pendente de expressões de default, CHECK/FK/índice, USING/WITH CHECK e detalhes semânticos de triggers. O parser não executa SQL; blocos DO e DML não são tratados como prova histórica. O catálogo completo permite revisão manual dos objetos não extraídos ou alterações condicionais. Presença estrutural não é equivalência semântica completa. Não foi identificado DRIFT nas declarações finais comparáveis.','','SUPERSEDED_BY_LATER_MIGRATION indica a última definição por objeto, sem dizer que tabelas ou histórico remanescentes desapareceram. Migration 30 contém diretamente o dashboard final corrigido; 29 remove o overload legado de paciente e seus grants. 31 expõe só metadados pending ao owner ativo, com gate global AND flag da organização; não concede workspace clínico.','','## Produção','','**DESIGN_READY_FOR_HUMAN_REVIEW**: ver [plano canônico](CLINIC_PRODUCTION_MIGRATION_PLAN.md). Todos os originais permanecem staging-only. Guards/bindings exigem PRODUCTION_EQUIVALENT_REQUIRED; nenhuma remoção automática, bundle SQL de produção ou aplicação foi realizada. Históricos 01–22 não serão falsificados.','','Evidência detalhada: [migration-provenance.json](clinic-f6-evidence/migration-provenance.json).'];
lines.splice(3,0,'O campo sha256 usa o conteúdo versionado UTF-8 com LF, estável entre Windows e Linux. checkout_sha256 no JSON preserva também o hash dos bytes locais desta execução; 01–22 tinham CRLF no checkout. Nenhum arquivo SQL original foi renormalizado nesta rodada.');
writeFileSync('docs/CLINIC_MIGRATION_PROVENANCE.md',lines.join('\n')+'\n');
console.log(JSON.stringify({ provenance01to22:report.provenance01to22,history23to30:report.history23to30, classifications:results.map(row=>({number:row.number,status:row.status,drift:row.objects.filter(object=>object.status==='DRIFT')})) }));
