-- Historical production migration alias.
--
-- Production executed this migration under version:
-- 20260921144237
--
-- The equivalent canonical migration in this repository is:
-- 20260921203000_allow_existing_completed_package_session_edits.sql
--
-- The SQL effects are already represented by the canonical migration.
-- This file intentionally performs no SQL so fresh databases do not
-- execute the same migration twice.
--
-- DO NOT add executable SQL to this historical alias.
