-- Lifecycle Automation: campanha e conteúdo inicial em draft.
-- A campanha não é ativada por esta migration.

INSERT INTO public.lifecycle_campaigns (key, name, description, campaign_type, status, enrollment_mode, eligible_from, timezone, default_send_time, max_messages_per_24h, completion_window_days)
VALUES
  ('new_user_activation_15d', 'Jornada de Ativação — Novos Usuários', 'Sequência educativa individual de 15 mensagens.', 'sequence', 'draft', 'new_users_only', now(), 'America/Sao_Paulo', '08:30', 1, 25),
  ('inactive_user_reactivation', 'Reativação de Usuários', 'Recuperação de usuários sem acesso recente.', 'reactivation', 'draft', 'selected_users', now(), 'America/Sao_Paulo', '08:30', 1, 30),
  ('trial_conversion', 'Conversão do Teste', 'Comunicações relacionadas ao fim real do teste de 7 dias.', 'conditional', 'draft', 'new_users_only', now(), 'America/Sao_Paulo', '08:30', 1, 14),
  ('customer_adoption', 'Adoção de Assinantes', 'Adoção de recursos por assinantes ativos.', 'customer', 'draft', 'selected_users', now(), 'America/Sao_Paulo', '08:30', 1, 30),
  ('cancellation_feedback', 'Feedback de Cancelamento', 'Coleta de motivo após solicitação de cancelamento.', 'conditional', 'draft', 'selected_users', now(), 'America/Sao_Paulo', '08:30', 1, 14)
ON CONFLICT (key) DO NOTHING;

INSERT INTO public.lifecycle_steps (campaign_id, step_key, position, day_offset, category, priority, status, subject_template, preheader_template, body_markdown, cta_label_template, cta_route_template, fallback_cta_route)
SELECT c.id, v.step_key, v.position, v.day_offset, v.category, 50, 'draft', v.subject_template, v.preheader_template, v.body_markdown, v.cta_label_template, v.cta_route_template, v.fallback_cta_route
FROM public.lifecycle_campaigns c
CROSS JOIN (VALUES
  ('day_01', 1, 1, 'activation', 'Seu próximo passo no Evolução Clínica', 'Acesse sua conta e continue de onde parou.', E'Olá, {{primeiro_nome}}!\n\nSua conta no Evolução Clínica está pronta. Nos próximos dias, você receberá orientações rápidas para conhecer os principais recursos e apoiar sua rotina de registros.\n\nVocê não precisa configurar tudo de uma vez. Hoje, acesse a plataforma e continue a primeira etapa do onboarding.\n\nA inteligência artificial apoia a organização e a redação; a conferência profissional continua essencial.', 'Continuar configuração', '/onboarding', '/painel/dashboard'),
  ('day_02', 2, 2, 'activation', 'Comece pelo seu primeiro paciente', 'Cadastre um paciente para iniciar a organização.', E'Olá, {{primeiro_nome}}!\n\nO cadastro do paciente é o primeiro passo para reunir evoluções, históricos e documentos. Comece com apenas um paciente para conhecer o funcionamento da plataforma.\n\nDepois do cadastro, a próxima etapa será criar ou vincular o prontuário no Google Docs.', 'Cadastrar primeiro paciente', '/painel/patients/new', '/painel/patients'),
  ('day_03', 3, 3, 'activation', 'Prepare o prontuário do seu paciente', 'Crie ou vincule um documento no Google Docs para continuar.', E'O paciente já está cadastrado.\n\nAgora, crie ou vincule o prontuário no Google Docs. Essa conexão permite organizar as evoluções concluídas no documento do paciente.\n\nDepois dessa etapa, você poderá gravar seu primeiro resumo e experimentar o fluxo completo.', 'Configurar prontuário', '/painel/patients', '/painel/patients'),
  ('day_04', 4, 4, 'activation', 'Transforme sua fala em uma evolução', 'Grave ou envie um resumo em áudio e confira o resultado.', E'Agora que existe um prontuário vinculado, experimente uma das principais propostas do Evolução Clínica.\n\nGrave ou envie um resumo em áudio. A inteligência artificial apoiará a transcrição e a organização da redação, e o resultado será adicionado ao prontuário.\n\nAntes de utilizar o conteúdo, confira se ele representa corretamente o atendimento e faça os ajustes necessários.', 'Criar primeira evolução', '/painel/patients', '/painel/dashboard'),
  ('day_05', 5, 5, 'education', 'Como preparar um bom resumo falado', 'Uma estrutura simples ajuda a organizar melhor o registro.', E'Você não precisa preparar um discurso perfeito.\n\nUma forma simples de organizar sua fala é mencionar o contexto do atendimento, os principais pontos observados, as atividades ou temas abordados, a resposta apresentada e os próximos passos.\n\nFale de forma natural e confira o conteúdo depois do processamento.', 'Gravar um resumo', '/painel/patients', '/painel/dashboard'),
  ('day_06', 6, 6, 'education', 'A IA organiza. Você continua no controle.', 'O texto organizado precisa representar corretamente o atendimento.', E'A inteligência artificial apoia a transcrição e a organização da redação. Ela não substitui sua análise, seu conhecimento nem sua responsabilidade profissional.\n\nConfira se o conteúdo representa o atendimento, se os termos estão adequados e se algo precisa ser ajustado. O conteúdo final continua sob seu controle.', 'Conferir meus registros', '/painel/history', '/painel/dashboard'),
  ('day_07', 7, 7, 'education', 'O histórico ajuda no próximo atendimento', 'Consulte os registros disponíveis do paciente.', E'Quando os registros ficam reunidos no prontuário, consultar informações anteriores se torna mais simples.\n\nO histórico pode ajudar a relembrar pontos do encontro anterior, acompanhar mudanças e manter continuidade entre atendimentos. Abra um paciente e consulte os registros disponíveis.', 'Consultar histórico', '/painel/history', '/painel/patients'),
  ('day_08', 8, 8, 'habit', 'Aproveite os minutos entre atendimentos', 'Use um pequeno intervalo para registrar os principais pontos.', E'Atendimentos consecutivos podem tornar difícil parar para escrever uma evolução completa.\n\nUma alternativa é gravar um resumo enquanto as informações ainda estão recentes. Depois do processamento, confira o conteúdo e continue sua rotina.', 'Registrar atendimento', '/painel/patients', '/painel/dashboard'),
  ('day_09', 9, 9, 'retention', 'A semana ficou corrida?', 'Comece por um único registro e avance aos poucos.', E'Em semanas cheias, algumas tarefas administrativas ficam para depois. Você não precisa resolver tudo de uma vez.\n\nEscolha um atendimento, grave um resumo com os principais pontos e conclua uma evolução. Uma ação pequena pode ser o começo da retomada.', 'Retomar meus registros', '/painel/patients', '/painel/dashboard'),
  ('day_10', 10, 10, 'habit', 'Um fechamento simples para o fim do dia', 'Confira rapidamente o que foi registrado e o que precisa ser retomado.', E'Uma rotina de fechamento pode ajudar a reduzir o acúmulo de registros.\n\nAntes de encerrar o dia, confira os pacientes atendidos, verifique quais evoluções foram concluídas e organize a próxima ação. Reunir essas informações em um fluxo pode reduzir a procura em diferentes arquivos.', 'Revisar minha rotina', '/painel/dashboard', '/painel/dashboard'),
  ('day_11', 11, 11, 'discovery', 'Conheça a área de documentos', 'Explore os recursos disponíveis na sua conta.', E'Além das evoluções, o Evolução Clínica possui recursos que podem apoiar a organização de documentos e relatórios.\n\nA disponibilidade depende do plano e da configuração da conta. Ao utilizar qualquer documento produzido com apoio da plataforma, confira o conteúdo e faça as adequações necessárias antes do uso.', 'Conhecer documentos', '/painel/history', '/painel/dashboard'),
  ('day_12', 12, 12, 'education', 'O que a inteligência artificial faz na plataforma', 'Entenda o papel da IA na organização dos registros.', E'No Evolução Clínica, a inteligência artificial é utilizada como apoio à transcrição, à organização e à redação das informações fornecidas.\n\nEla não realiza diagnóstico, define condutas, substitui o raciocínio profissional nem elimina a necessidade de conferência. A proposta é reduzir tarefas repetitivas, mantendo sua experiência no centro do processo.', 'Criar nova evolução', '/painel/patients', '/painel/dashboard'),
  ('day_13', 13, 13, 'discovery', 'Explore outra possibilidade da plataforma', 'Conheça um recurso disponível para o seu plano.', E'Existe um recurso adicional que pode complementar sua rotina.\n\nExplore somente funcionalidades disponíveis na sua conta e confirme o conteúdo antes de utilizá-lo. O recurso recomendado pode variar conforme seu estágio e seu plano.', 'Explorar recurso', '/painel/profile', '/painel/dashboard'),
  ('day_14', 14, 14, 'retention', 'Veja o que você já começou a organizar', 'Continue de onde parou pela próxima ação recomendada.', E'Olá, {{primeiro_nome}}!\n\nDesde que sua conta foi ativada, você já:\n\n- cadastrou {{quantidade_pacientes}} paciente(s);\n- vinculou {{quantidade_prontuarios}} prontuário(s);\n- concluiu {{quantidade_evolucoes}} evolução(ões).\n\nA próxima ação recomendada é: {{proxima_acao}}.', '{{proxima_acao}}', '{{link_acao}}', '/painel/dashboard'),
  ('day_15', 15, 15, 'retention', 'A jornada termina. Sua organização continua.', 'As mensagens terminam, mas o uso continua na sua rotina.', E'Olá, {{primeiro_nome}}!\n\nChegamos à última mensagem desta jornada de apresentação. Você conheceu os principais passos para cadastrar pacientes, vincular prontuários, gravar evoluções e consultar históricos.\n\nA melhor forma de perceber o valor da plataforma é utilizá-la nos momentos reais da rotina. A inteligência artificial apoia a organização e a redação; você continua no controle do conteúdo final.', '{{proxima_acao}}', '{{link_acao}}', '/painel/dashboard')
) AS v(step_key, position, day_offset, category, subject_template, preheader_template, body_markdown, cta_label_template, cta_route_template, fallback_cta_route)
WHERE c.key = 'new_user_activation_15d'
ON CONFLICT (campaign_id, step_key) DO NOTHING;
