-- Lifecycle Automation: regras conhecidas. O avaliador é fechado no TypeScript.

INSERT INTO public.lifecycle_rules (rule_key, name, description, trigger_event, rule_type, priority, cooldown_hours, delay_minutes, condition_config, message_config)
VALUES
('no_return_after_registration', 'Conta ativa sem novo acesso', 'Conta ativa sem login após 24 horas.', NULL, 'inactivity', 80, 24, 0, '{"minimum_hours":24}'::jsonb, '{"subject":"Sua conta está pronta para continuar","preheader":"Acesse a plataforma e continue pela primeira etapa.","body":"Sua conta no Evolução Clínica já está disponível. Acesse a plataforma e comece por uma ação simples.","cta_label":"Acessar minha conta","cta_route":"/painel/dashboard","category":"activation"}'::jsonb),
('logged_in_without_patient', 'Acessou sem cadastrar paciente', 'Login realizado, mas nenhum paciente cadastrado.', NULL, 'state', 80, 24, 0, '{}'::jsonb, '{"subject":"Falta apenas o primeiro paciente para começar","preheader":"Cadastre um paciente para iniciar a organização.","body":"Você já acessou o Evolução Clínica. O próximo passo é cadastrar um paciente para iniciar a organização dos prontuários e evoluções.","cta_label":"Cadastrar primeiro paciente","cta_route":"/painel/patients/new","category":"activation"}'::jsonb),
('patient_without_linked_record', 'Paciente sem prontuário', 'Há pacientes, mas nenhum prontuário do Google Docs vinculado.', NULL, 'state', 85, 24, 0, '{}'::jsonb, '{"subject":"Seu paciente já está cadastrado. Falta o prontuário.","preheader":"Crie ou vincule o prontuário antes da primeira evolução.","body":"O paciente já foi cadastrado. Antes de criar a primeira evolução, crie ou vincule o prontuário no Google Docs.","cta_label":"Configurar prontuário","cta_route":"/painel/patients","category":"activation"}'::jsonb),
('linked_record_without_evolution', 'Prontuário sem evolução', 'Prontuário vinculado sem evolução concluída após 24 horas.', NULL, 'state', 90, 24, 0, '{}'::jsonb, '{"subject":"Seu prontuário está pronto para a primeira evolução","preheader":"Grave ou envie um resumo em áudio.","body":"O prontuário já está vinculado. Agora, grave ou envie um resumo em áudio para experimentar o fluxo completo.","cta_label":"Criar primeira evolução","cta_route":"/painel/patients","category":"activation"}'::jsonb),
('evolution_processing_too_long', 'Evolução em processamento', 'Evolução pendente além do limite técnico esperado.', NULL, 'state', 95, 24, 120, '{}'::jsonb, '{"subject":"Sua evolução ainda está em processamento","preheader":"Acesse a plataforma para verificar o status.","body":"Uma evolução iniciada ainda não foi concluída. Acesse a plataforma para verificar o status e procurar o suporte se necessário.","cta_label":"Verificar evolução","cta_route":"/painel/history","category":"technical"}'::jsonb),
('first_evolution_completed', 'Primeira evolução concluída', 'Primeira evolução concluída sem e-mail operacional equivalente.', 'evolution_completed', 'event', 85, 0, 0, '{}'::jsonb, '{"subject":"Sua primeira evolução foi concluída","preheader":"Confira como o registro ficou organizado.","body":"Sua primeira evolução foi processada e adicionada ao prontuário. Consulte o histórico e continue utilizando a plataforma.","cta_label":"Ver histórico","cta_route":"/painel/history","category":"activation"}'::jsonb),
('trial_expiring_3d', 'Teste termina em três dias', 'Aviso comercial três dias antes do fim do trial.', 'trial_expiring', 'deadline', 90, 120, 0, '{"days_before":3}'::jsonb, '{"subject":"Seu período de teste termina em 3 dias","preheader":"Conheça as opções para continuar.","body":"Seu período de teste termina em {{data_fim_teste}}. Você já cadastrou {{quantidade_pacientes}} paciente(s) e concluiu {{quantidade_evolucoes}} evolução(ões). Conheça as opções disponíveis.","cta_label":"Conhecer os planos","cta_route":"/painel/subscription","category":"commercial","commercial":true}'::jsonb),
('trial_expiring_1d', 'Teste termina amanhã', 'Aviso comercial um dia antes do fim do trial.', 'trial_expiring', 'deadline', 90, 120, 0, '{"days_before":1}'::jsonb, '{"subject":"Seu teste termina amanhã","preheader":"Continue com o Evolução Clínica.","body":"Seu período de teste termina amanhã. Conheça os planos disponíveis para continuar utilizando os recursos da sua conta.","cta_label":"Continuar com o Evolução Clínica","cta_route":"/painel/subscription","category":"commercial","commercial":true}'::jsonb),
('trial_expired', 'Teste encerrado', 'Mensagem no encerramento do trial.', 'trial_expired', 'deadline', 90, 120, 0, '{}'::jsonb, '{"subject":"Seu período de teste terminou","preheader":"Escolha uma opção de continuidade.","body":"Seu período de teste do Evolução Clínica terminou. Para continuar utilizando os recursos disponíveis, escolha um dos planos apresentados na plataforma.","cta_label":"Escolher um plano","cta_route":"/painel/subscription","category":"commercial","commercial":true}'::jsonb),
('trial_recovery_2d', 'Recuperação dois dias após o teste', 'Recupera usuários que ainda não assinaram.', 'trial_expired', 'deadline', 80, 120, 0, '{"days_after":2}'::jsonb, '{"subject":"Continue de onde você parou","preheader":"Retome sua organização quando estiver pronto.","body":"Você já começou a organizar sua rotina no Evolução Clínica. Se desejar continuar utilizando pacientes, prontuários e evoluções, escolha um plano e retome sua conta.","cta_label":"Retomar minha conta","cta_route":"/painel/subscription","category":"commercial","commercial":true}'::jsonb),
('trial_recovery_7d', 'Recuperação sete dias após o teste', 'Última recuperação do ciclo inicial.', 'trial_expired', 'deadline', 80, 168, 0, '{"days_after":7}'::jsonb, '{"subject":"O que impediu você de continuar?","preheader":"Conte o que dificultou sua continuidade.","body":"Gostaríamos de entender se algo dificultou sua continuidade: falta de tempo, Google, primeira evolução, preço ou outra necessidade.","cta_label":"Contar o que aconteceu","cta_route":"/painel/support","category":"commercial","commercial":true}'::jsonb),
('inactive_3d', 'Três dias sem acesso', 'Reativação leve após três dias sem login.', NULL, 'inactivity', 60, 72, 0, '{"days":3}'::jsonb, '{"subject":"Continue de onde você parou","preheader":"Retome a próxima ação recomendada.","body":"Acesse sua conta e continue pela próxima ação recomendada.","cta_label":"Continuar de onde parei","cta_route":"/painel/dashboard","category":"reactivation"}'::jsonb),
('inactive_7d', 'Sete dias sem acesso', 'Reativação após uma semana sem login.', NULL, 'inactivity', 70, 168, 0, '{"days":7}'::jsonb, '{"subject":"A semana ficou corrida?","preheader":"Comece por apenas uma ação.","body":"Se os registros ficaram para depois, abra a plataforma e retome um atendimento de cada vez.","cta_label":"Retomar meus registros","cta_route":"/painel/patients","category":"reactivation"}'::jsonb),
('inactive_14d', 'Quatorze dias sem acesso', 'Identifica possível dificuldade de uso.', NULL, 'inactivity', 75, 336, 0, '{"days":14}'::jsonb, '{"subject":"Algo dificultou o uso da plataforma?","preheader":"Estamos disponíveis para ajudar.","body":"Gostaríamos de saber se você encontrou dificuldade no Google, na primeira evolução, no tempo disponível ou em algum recurso.","cta_label":"Preciso de ajuda","cta_route":"/painel/support","category":"reactivation"}'::jsonb),
('subscription_started', 'Assinatura concluída', 'Confirmação e entrada no fluxo de adoção.', 'subscription_started', 'event', 100, 0, 0, '{}'::jsonb, '{"subject":"Sua assinatura do Evolução Clínica está ativa","preheader":"As próximas mensagens ajudarão na adoção da sua conta.","body":"Sua assinatura foi confirmada. Você pode continuar utilizando os recursos disponíveis no seu plano.","cta_label":"Acessar minha conta","cta_route":"/painel/dashboard","category":"transactional"}'::jsonb),
('subscriber_low_usage', 'Assinante com baixo uso', 'Assinante ativo com baixa utilização após sete dias.', NULL, 'state', 80, 168, 0, '{"days":7}'::jsonb, '{"subject":"Vamos aproveitar melhor sua assinatura?","preheader":"Escolha uma ação simples para retomar.","body":"Sua assinatura está ativa. Escolha uma ação simples: cadastrar paciente, vincular prontuário, criar evolução ou conhecer um recurso do seu plano.","cta_label":"Continuar usando","cta_route":"/painel/dashboard","category":"retention"}'::jsonb)
ON CONFLICT (rule_key) DO NOTHING;
